# Areas by path (relative to repo root)
service:
  - changed-files:
      - any-glob-to-any-file: services/**

frontend:
  - changed-files:
      - any-glob-to-any-file: "**/frontend/**"
      
configuration:
  - changed-files:
      - any-glob-to-any-file: "*.yml"

documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**
      - any-glob-to-any-file: "**/*.md"

# Branch prefixes (Trunk-Based)
feature:
  - head-branch: ["^feat", "feat"]

bug:
  - head-branch: ["^fix", "fix"]
