version: "3.9"

services:

  caddy:
    image: caddy:2-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  courier-service:
    image: ${DOCKER_USER}/courier-service:${COURIER_SERVICE_TAG}
    ports:
      - "7070:7070"
    depends_on:
      - rabbitMQ
      - redis-active-db
      - sql-driver
    deploy:
      replicas: 1
    networks:
      - backend

  customer-service:
    image: ${DOCKER_USER}/customer-service:${CUSTOMER_SERVICE_TAG}
    ports:
      - "7071:7070"
    depends_on:
      - rabbitMQ
      - redis-active-db
      - sql-driver
    deploy:
      replicas: 1
    networks:
      - backend

  management-service:
    image: ${DOCKER_USER}/management-service:${MANAGEMENT_SERVICE_TAG}
    ports:
      - "7072:7070"
    depends_on:
      - rabbitMQ
      - sql-driver
    deploy:
      replicas: 1
    networks:
      - backend

  supplier-service:
    image: ${DOCKER_USER}/supplier-service:${SUPPLIER_SERVICE_TAG}
    ports:
      - "7073:7070"
    depends_on:
      - rabbitMQ
      - redis-active-db
      - sql-driver
    deploy:
      replicas: 1
    networks:
      - backend

  support-service:
    image: ${DOCKER_USER}/support-service:${SUPPORT_SERVICE_TAG}
    ports:
      - "7074:7070"
    depends_on:
      - mongo-driver
      - rabbitMQ
    deploy:
      replicas: 1
    networks:
      - backend

  rabbitMQ:
    image: rabbitmq:3.13-alpine
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - backend

  redis-active-db:
    image: redis:8.2.3-alpine
    networks:
      - backend

  redis-driver:
    image: ${DOCKER_USER}/redis-driver:${REDIS_DRIVER_TAG}
    depends_on:
      - redis-active-db
    networks:
      - backend

  MToGo-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${MTOGO_USER}
      POSTGRES_PASSWORD: ${MTOGO_PASS}
      POSTGRES_DB: ${MTOGO_DB}
    volumes:
      - mtogo_data:/var/lib/postgresql/data
    networks:
      - backend

  metrics-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${METRICS_USER}
      POSTGRES_PASSWORD: ${METRICS_PASS}
      POSTGRES_DB: ${METRICS_DB}
    volumes:
      - metrics_data:/var/lib/postgresql/data
    networks:
      - backend

  sql-driver:
    image: ${DOCKER_USER}/sql-driver:${SQL_DRIVER_TAG}
    depends_on:
      - MToGo-db
      - metrics-db
    networks:
      - backend

  support-db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SUPPORT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SUPPORT_PASS}
    volumes:
      - support_data:/data/db
    networks:
      - backend

  applicant-db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APPLICANT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APPLICANT_PASS}
    volumes:
      - applicant_data:/data/db
    networks:
      - backend

  mongo-driver:
    image: ${DOCKER_USER}/mongodb-driver:${MONGODB_DRIVER_TAG}
    depends_on:
      - support-db
      - applicant-db
    networks:
      - backend

networks:
  backend:
    driver: overlay

volumes:
  mtogo_data:
  metrics_data:
  support_data:
  applicant_data:
  caddy_data:
  caddy_config:
