{
 "title": "MTOGO Resources",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Replica Amount Per Service",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (service) (\n  label_replace(\n    container_start_time_seconds{\n      container_label_com_docker_swarm_service_name!=\"\"\n    },\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Summed by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (service) (\n  label_replace(\n    rate(container_cpu_usage_seconds_total{\n      container_label_com_docker_swarm_service_name!=\"\",\n    }[1m]),\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Summed By Service (GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (\n  label_replace(\n    container_memory_working_set_bytes{\n      container_label_com_docker_swarm_service_name!=\"\"\n    } / 1024 / 1024 / 1024,\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received Per Service (Kb/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (service) (\n  label_replace(\n    rate(container_network_receive_bytes_total{\n      container_label_com_docker_swarm_service_name!=\"\",\n    }[1m]) / 1024,\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmitted Per Service (Kb/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (service) (\n  label_replace(\n    rate(container_network_transmit_bytes_total{\n      container_label_com_docker_swarm_service_name!=\"\",\n    }[1m]) / 1024,\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Reads Per Service (Kb/m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (service) (\n  label_replace(\n    rate(container_fs_reads_bytes_total{\n      container_label_com_docker_swarm_service_name!=\"\",\n    }[1m]) / 1024,\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Writes Per Service (Kb/m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (service) (\n  label_replace(\n    rate(container_fs_writes_bytes_total{\n      container_label_com_docker_swarm_service_name!=\"\",\n    }[1m]) / 1024,\n    \"service\",\n    \"$1\",\n    \"container_label_com_docker_swarm_service_name\",\n    \"mtogo-system_(.*)\"\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}