title: "Sub Issue"
labels: ["feature", "priority:High", "priority:Medium", "priority:Low"]
fields:
  automation:
    type: string # is default type, not needed
    value: |
      [{
          "trigger": "on:close",
          "action": {
              "type": "set-field",
              "field": "status",
              "value": "done"
          },
          "targets": ["self"]
      },
      {
          "trigger": "on:close",
          "action": {
              "type": "set-field",
              "field": "custom field",
              "value": "custom value after close of 'My 1st Sub-Issue'"
          },
          "targets": ["self", "parent"]
      },
      {
          "trigger": "on:close",
          "action": {
              "type": "set-field",
              "field": "custom date field",
              "field-type": "date",
              "value": "2025-01-01"
          },
          "targets": ["self", "parent"]
      }]
  custom field:
    value: value from template for 'My 1st Sub-Issue'
  custom date field:
    value: 2023-10-01
    type: date
  status:
    value: Custom status
    type: selection # this is also inferred automatically for selection fields
